---
title: "参考文献"
---


## 第2章 集団安全保障体制の系譜

- Boutros-Ghali, B. (1992) An Agenda for Peace. United Nations, No. A/47/277, S/24111, <https://digitallibrary.un.org/record/146039>
- Boutros-Ghali, B. (1995) Supplement to an Agenda for Peace. United Nations, No. A/50/60, S/1995/1, <https://www.un.org/en/documents/sg/agenda/supplement.shtml>
- 国際連合広報センター (1995) 平和への課題 1995年. <https://www.unic.or.jp/files/peace.pdf>
- Urquhart, Brian (1994) *The UN and International Security after the Cold War*. Clarendon Press, Oxford
- 香西 茂 (1991) *国連の平和維持活動*. 有斐閣
- 西川 吉光 (1996) *紛争解決と国連・国際法*. 晃洋書房
- 石塚 勝美 (2011) *国連PKOと国際政治*. 創成社
- 福田 菊 (1994) *国連とPKO―「戦わざる軍隊」のすべて*. 東信堂, 第二版
- 甲山 員司 (1999) 「冷戦後の国際平和維持活動（PKO): PKOの有効性と限界について」
- 篠田 英朗 (2001) 「国際規範の歴史的・理論的検討 秩序・正義そして国家主権」
- 筒井 若水 (1994) 「集団安全保障と安全保障理事会の役割」. *世界法年報*(14), pp. 23-36
- 香西 茂 (1992) 「ポスト冷戦期における国連の役割」. *戦争と平和 : 大阪国際平和研究所紀要* 1(1), pp. 13-20
- 香西 茂 (1993) 「国際連合の紛争処理機能の動向」. *国際問題* 390
- 香西 茂 (1995) 「国連と世界平和の維持―――五○年の変遷と課題」. *国際問題* 428, pp. 26-27
- 鴨 武彦 (1995) 「ポスト冷戦下の国際連合————国際安全保障機能および役割の変化と改革構想」. *“国際法外交雑誌”* “94”
- 鴨 武彦 (1993) 「冷戦後の安全保障と国連 理論的考察」. *“平和研究”* “18”, pp. “63-72”
- 松田 竹男 (1995) 国際連合の集団安全保障 ――その歴史、現状、課題
- 酒井 啓亘 (1996) 「国連平和維持活動の今日的展開と原則の動揺」. *国際法外交雑誌* 94(5), pp. 667-690
- 土屋 茂樹 (1990) 「勢力均衡政策と集団安全保障」. *滋賀大学教育学部紀要*, pp. 33-54
- 松葉 真美 (2010) 「国連平和維持活動（PKO)の発展と武力行使をめぐる原則の変化」. *レファレンス* 60(1)
- 高井 晉 (2002) 紛争解決支援と軍事力の役割. 防衛研究所
- Roberts, A. (1994) 「The Crisis in UN Peacekeeping」. *Survival* 36(3), pp. 102-104
- Thadoor, S. (1995) 「Should UN Peacekeeping Go 'Back to Basic'?」. *Survival* 37(4)
- Annan, K. (1993) 「UN Peacekeeping Operation and Cooperation with NATO」. *NATO Review* 41(5)
- Mackenzie, L. (1992) 「Military Realities of UN Peacekeeping Operations」. *A presentation paper to Royal United Service Institute for Defence Studies （RUSI)*

## 第3章 争点・論点解説

- 佐藤 哲夫 (2011) 「見果てぬ夢、国連常設軍 —国際公共目的に向けた軍事的強制の現代的諸相—」. *世界法年報 = Yearbook of world law / 世界法学会 編*(30), pp. 1-51
- 阪口 規純 (2007) 「国連の緊急展開能力強化と常設軍構想の意義・限界」. *国際公共政策研究* 12(1), pp. 93-109
- 一政 祐行 (2003) 「国連PKO待機制度の現状とその展望 ―待機軍即応旅団（SHIRBRIG）―」. *外務省調査月報*(2002年度(3)), pp. 79-117

## 第4章 国連による紛争処理

- 横田洋三 (2000) *国連による平和と安全の維持 : 解説と資料 第1巻*. 国際書院
- 横田洋三 (2007) *国連による平和と安全の維持 : 解説と資料 第2巻*. 国際書院
- マラック・アーヴィン・グールディング (2005) *国連の平和外交 : PEACEMONGER*. 東信堂
- 三菱UFJリサーチ&コンサルティング株式会社 (2013) 安保理決議による経済制裁：制裁に至る事情・内容・効果等の横断的比較分析報告書. 三菱UFJリサーチ&コンサルティング, <https://www.mofa.go.jp/mofaj/gaiko/jp_un/pdfs/itaku_1303.pdf>

## 第5章 国連の制度

- Simma, Bruno (ed.) (2012) *The Charter of the United Nations: A Commentary*. Oxford University Press, 3rd edition
- United Nations (1970) Repertory of Practice of United Nations Organs, Supplement No. 4 (1966-1969), Volume I. <https://legal.un.org/repertory/>
- United Nations (1980) Repertory of Practice of United Nations Organs, Supplement No. 5 (1970-1978), Volume II. <https://legal.un.org/repertory/>
- Boudreau, Donald G. (1998) 「UN sanctions burden sharing: Article 50 of the UN charter and assistance to third states」. *Diplomacy & Statecraft* 9(1), pp. 24-52
- Cefkin, J. Leo (1968) 「The Rhodesian Question at the United Nations」. *International Organization* 22(3), pp. 649-669
- Boisson de Chazournes, Laurence (2007) 「Collective Security and the Economic Interventionism of the UN: the need for a coherent and Integrated Approach」. *Journal of International Economic Law* 10(1), pp. 51-86
- 村瀬信也（編） (2009) *国連安保理の機能変化*. 東信堂
- Chayes, Abram and Chayes, Antonia H.（宮野洋一監訳） (2018) *国際法遵守の管理モデル：新しい主権のあり方*. 中央大学出版部
- 本多美樹 (2017) *経済制裁の研究：経済制裁の政治経済学的位置付け*. 志學社
- Global Policy Forum Sanctions: An Analysis. <https://archive.globalpolicy.org/component/content/article/202-sanctions/41612-sanctions-an-analysis.html>
- Lopez, George A. (2001) 「Sanctions and the rule of law: Severe ethical and practical challenges」. *International Studies Association (ISA) 2001 Annual Convention*, <https://ciaotest.cc.columbia.edu/isa/log01/>


### 第1節 国連安保理による非軍事的強制措置の法的諸問題

- 吉村祥子 (2018) *国連の金融制裁：法と実務*. 東信堂
- 吉村祥子 (2003) *国連非軍事的制裁の法的問題*. 国際書院
- 松隈潤 (2006) 「経済制裁の法的規制」. *西南学院大学法学論集* 39(1), pp. 113-122
- de Wet, Erika (2004) *The Chapter VII Powers of the United Nations Security Council*. Hart Publishing
- Sarooshi, Dan (1999) *The United Nations and the Development of Collective Security*. Oxford University Press
- Cortright, David and Lopez, George A. (2002) *Smart Sanctions: Targeting Economic Statecraft*. Rowman & Littlefield
- Conlon, Paul (2000) *United Nations Sanctions Management: A Case Study of the Iraq Sanctions Committee 1990-1994*. Transnational Publishers
- 中谷和弘 (1990) 「イラクに対する経済制裁」. *法学セミナー* 1990年11月号, pp. 24-27
- 中谷和弘 (1991) 「経済制裁と国際公益 – 第三国との関係を中心として–」. *国際法と国内法 – 国際公益の展開– （山本草二先生還暦記念）*, pp. 535-561
- 中谷和弘 (1992) 「パンナム103便およびUTA772便爆破事件と国際社会の対応 – 国連安全保障理事会決議731をめぐって」. *ジュリスト* 998, pp. 82-86
- 中谷和弘 (1995) 「国際法の観点からみた経済制裁」. *論文から見る現代社会と法*, pp. 219-250
- 中谷和弘 (1996) 「湾岸戦争の事後救済機関としての国連補償委員会」. *国際社会の組織化と法（内田久司先生古希記念）*, pp. 333-363
- 中谷和弘 (2009) 「安保理決議に基づく経済制裁ー近年の特徴と法的課題ー」. *国連安保理の機能変化*, pp. 79-96
- 三菱UFJリサーチ＆コンサルティング（編） (2013) 委託研究 安保理決議による経済制裁：制裁に至る事情・内容・効果等の横断的比較分析. 三菱UFJリサーチ＆コンサルティング株式会社
- 中谷和弘 (2022) 経済制裁の国際法構造. 日本国際問題研究所
- 儀村英司 (2001) 「国連補償委員会の法的性格：その設立根拠と準司法的機能をめぐって」. *西南学院大学大学院法学研究論集* 19, pp. 101-136
- 権南希 (2015) 「武力紛争による環境損害の賠償メカニズムの制度化：国連補償委員会における環境損害請求の特徴を中心に」. *国際法外交雑誌* 114(2)
- United Nations (1994) Yearbook of the United Nations 1994
- United Nations (1995) Yearbook of the United Nations 1995
- Brand, Ronald A. (1976) 「Security Council Resolutions: When Do They Give Rise to Enforceable Legal Rights?」. *Cornell International Law Journal* 9, pp. 298
- Rajčić, Ivana (2014) 「Legal Control over Decisions Taken by the United Nations Organs and Judicial Review of the Security Council Decisions」. *Pravnik* 47(96)
- 松浦博司 (2005) *国連安全保障理事会：その限界と可能性*. 新風舎
- 鈴木隆 (2006) 「安保理機能の拡大とその限界：国連安保理による非軍事的強制措置の決定について」. *レファレンス（国立国会図書館）*(662)
- Wood, Michael C. (1996) 「Security Council Working Methods and Procedure: Recent Developments」. *International and Comparative Law Quarterly* 45, pp. 150-161
- Hulton, Susan C. (1996) 「Security Council Working Methods: Provisional Progress」. *Cambridge Law Journal* 55(1)
- 川嶋隆志 (2014) *人権保障による平和構築*. デザインエッグ社
- United Nations Information Service (Vienna) Introduction. <https://unis.unvienna.org/unis/en/united_nations/un_introduction.html>
- Subsidiary Organs of the General Assembly. <https://www.un.org/en/ga/about/subsidiary/committees.shtml>
- 外務省：国連総会. <https://www.mofa.go.jp/mofaj/gaiko/unsokai/index.html>
- The Secretariat: Structure and Composition. <https://www.nationsencyclopedia.com/United-Nations/The-Secretariat-STRUCTURE-AND-COMPOSITION-OF-THE-SECRETARIAT.html>
- EJIL Article (Review of Sarooshi). <https://www.ejil.org/pdfs/16/5/329.pdf>


### 第2節 国連財政と憲章解釈

- Kelsen, Hans (1950) *The Law of the United Nations: A Critical Analysis of Its Fundamental Problems*. Stevens & Sons
- 田所昌幸 (1996) *国連財政：予算から見た国連の実像*. 有斐閣


### 第3節 PKOと人道的介入

- Browne, Marjorie Ann (1990) Military Component of United Nations Peace-keeping Operations. Congressional Research Service (CRS), No. IB90103
- Barnett, Michael（著）、田所昌幸ほか（訳） (2003) *国連はなぜルワンダを救えなかったのか*. 岩波書店
- Melvern, Linda (2000) *A People Betrayed: The Role of the West in Rwanda's Genocide*. Zed Books
- Wedgwood, Ruth (1995) 「The Evolution of United Nations Peacekeeping」. *Cornell International Law Journal* 28, pp. 631
- Holt, Victoria and Taylor, Glyn (2009) Protecting Civilians in the Context of UN Peacekeeping Operations. DPKO/OCHA, <https://peacekeeping.un.org/en/protecting-civilians>
- Government of Canada (1995) Towards a Rapid Reaction Capability for the United Nations
- Langille, H. Peter (2000) 「Conflict Prevention: Options for Rapid Deployment and UN Standing Forces」. *International Peacekeeping* 7(1), pp. 219-253


### 第4節 経済制裁の事例研究

- Bamber, David, Saleh, Farsat and Panditharathna, Roshan (2023) 「The Iraqi Oil Industry: History and Overview」. *European Journal of Political Science Studies* 6(1), <https://oapub.org/soc/index.php/EJPSS/article/view/1424>
- Rossignol, Michel (1996) Sanctions: The Economic Weapon in the New World Order. Library of Parliament, Canada, No. BP-346E
- Cortright, David and Lopez, George A. (2000) *The Sanctions Decade: Assessing the UN Experience of the 1990s*. Lynne Rienner Publishers
- 本多美樹 (2003) *国連による経済制裁と人道上の諸問題：スマート・サンクションの模索*. 国際書院
- U.S. General Accounting Office (GAO) (1994) Humanitarian Intervention: Effectiveness of U.N. Operations in Bosnia. No. GAO/NSIAD-94-156BR
- Operation LANCE (UNAMIR). <https://www.canada.ca/en/department-national-defence/services/military-history/history-heritage/past-operations/africa/lance-unamir.html>
- MERIP (1991) 「Economic Impact of the Crisis in Egypt」. *Middle East Report*, <https://www.merip.org/1991/01/economic-impact-of-the-crisis-in-egypt/>
- MERIP (2020) 「The Enduring Lessons of the Iraq Sanctions」. *Middle East Report Online*, <https://www.merip.org/2020/06/the-enduring-lessons-of-the-iraq-sanctions/>
- Human Rights Watch (2000) Iraq: Human Rights Watch Backgrounder. <https://www.hrw.org/legacy/press/2000/01/iraq-memo.htm>
- U.S. House Committee on Ways and Means (1992) Foreign Contributions to the Costs of the Persian Gulf War. U.S. Government Printing Office
- Rubin, Barry (2001) 「Sanctions on Iraq: A Valid Anti-American Grievance?」. *MERIA Journal* 5(4), <https://web.archive.org/web/20060907153101/http://meria.idc.ac.il/journal/2001/issue4/mrubin.pdf>
- Delevic, Milica (1998) 「Economic Sanctions as a Foreign Policy Tool: The Case of Yugoslavia」. *International Journal of Peace Studies* 3(1), <https://www3.gmu.edu/programs/icar/ijps/vol3_1/Delvic.htm>
- ODI Humanitarian Practice Network Sanctions and the Federal Republic of Yugoslavia. <https://odihpn.org/en/publication/sanctions-and-the-federal-republic-of-yugoslavia-assessing-impacts-and-drawing-lessons/>
- Global Policy Forum (1996) Report of the Copenhagen Round Table on United Nations Sanctions in the Case of the Former Yugoslavia. <https://archive.globalpolicy.org/component/content/article/202-sanctions/42472-report-of-the-copenhagen-round-table-on-united-nations-sanctions-in-the-case-of-the-former-yugoslavia.html>
- 川西晶大 (2020) 「リビアに対する経済制裁とその帰結」. *外国の立法*(283)
- Grenville-Wood, Geoffrey (1993) 「Sanctions Against Libya Set a Questionable Precedent」. *Bulletin of the United Nations Association in Canada*
- Human Rights Watch (1993) Human Rights Watch World Report 1993 - Haiti. <https://www.refworld.org/reference/annualreport/hrw/1993/en/93501>
- Garfield, Richard (1999) The Impact of Economic Sanctions on Health and Well-being. Overseas Development Institute, No. 31
- Harvard Center for Population and Development Studies (1994) The Impact of Economic Sanctions on Health and Human Rights in Haiti, 1991-1994
- 伊豆久 (2023) 「IMF融資条件の構造改革化と国際金融システム（下・その5）」. *久留米大学経済社会研究*
- U.S. Department of State Archive: Namibia. <https://2001-2009.state.gov/r/pa/ho/time/pcw/98678.htm>
- Foreign Relations of the United States, 1951, Volume I. <https://history.state.gov/historicaldocuments/frus1951v01/d222>
- Maritime Interception Operations (MIO). <https://www.globalsecurity.org/military/ops/mio.htm>
- Campaign Against Sanctions on Iraq (CASI). <https://www.casi.org.uk/info/themes.html#hum>
- How much did the Gulf War cost the US. <https://web.archive.org/web/20100821200403/http://people.psych.cornell.edu/~fhoran/gulf/GW_cost/GW_payments.html>
- Office of the Iraq Programme Fact Sheet. <https://www.un.org/depts/oip/background/fact-sheet.html>

## 第6章 その他の関連国際法


### 第1節 国際法基礎

- 山本草二、古川照美、松井芳郎 (2001) *国際法判例百選（初版）*. 有斐閣
- 該当会議フロント (2024) KMUNC24 コソボ情勢会議 BG


### 第2節 国家責任法

- International Law Commission (1996) Draft articles on State Responsibility adopted by the International Law Commission on first reading. United Nations, <https://legal.un.org/ilc/texts/instruments/english/commentaries/9_6_1996.pdf>
- 岩月直樹 (2003) 「対抗措置制度における均衡性原則の意義 : 均衡性原則の多元的把握へ向けての予備的考察」. *東京大学学術機関リポジトリ*
- 吉野宏美 (1994) 「国家責任法における『国家の国際犯罪』―集団責任の問題を中心として」. *本郷法改紀要*(3), pp. 393-397


### 第3節 国際経済法

- 中谷和弘 (2022) 国際法から見た経済制裁. <https://www.jiia.or.jp/pdf/research/R04_Economic_Security/01-02.pdf>
- 中谷和弘 (2022) 経済制裁の国際法構造. <https://www.jiia.or.jp/pdf/research/R04_Economic_Security/01-02.pdf>
- 阿部克則 (2020) 「ポスト・グローバリゼーションにおける安全保障例外条項」. *金融財政経済論叢*(155), <https://www.mof.go.jp/pri/publication/financial_review/fr_list8/r155/r155_4.pdf>
- 山岡加奈子 (2000) 「米国の対キューバ経済制裁―ヘルムズ・バートン法成立以降の米国政府内の議論を中心に」. *アジア経済* XLI(9), pp. 3-36
- Segall, Arnaldo (1999) 「Economic Sanctions: Legal and Policy Constraints」. *International Review of the Red Cross (IRRC)* 81(836), pp. 867-897
- 本多美樹 (2013) *国連による経済制裁と人道上の諸問題:「スマート・サンクション」の模索*. 国際書院
- 吉村祥子 (2003) *国連非軍事的制裁の法的問題*. 国際書院
