::: {.aj-index}

::: {.aj-index__block}
## PKOと即応体制

- <span class="aj-index__entry"><span class="aj-index__term">PKO特別委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-292-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-292-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-292-01">3節9項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-377-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-377-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-377-01">3節10項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-449-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-449-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-449-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKOと国連憲章の関係</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-365-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-365-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-365-01">3節9項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKOの制約</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-735-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-735-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-735-01">②PKOの制約</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKOの部隊構成</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-251-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-251-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-251-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKOへの各国貢献</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-438-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-438-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-438-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章39条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-737-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-737-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-737-01">③強制措置における正統性の制約</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章41条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-737-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-737-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-737-02">③強制措置における正統性の制約</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章43条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-368-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-368-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-368-01">3節10項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国連軍構想の失敗</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-153-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-153-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-153-01">3節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国連待機軍</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-366-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-366-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-366-01">3節10項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-380-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-380-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-380-01">3節10項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">即応部隊の撤退</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-091-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-091-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-091-01">2節3項</a></span></span></span>
:::

::: {.aj-index__block}
## その他の国際法

- <span class="aj-index__entry"><span class="aj-index__term">GATT協定</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-155-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-155-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-155-01">4節</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">安全保障例外</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-170-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-170-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-170-01">4節</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対抗措置</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-031-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-031-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-031-01">1節3項</a></span><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-072-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-072-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-072-01">2項</a></span><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-095-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-095-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-095-01">2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">内政不干渉原則</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-012-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-012-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-012-01">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">連盟規約　第16条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-295-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-295-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-295-01">4節1項</a></span></span></span>
:::

::: {.aj-index__block}
## その他の文書

- <span class="aj-index__entry"><span class="aj-index__term">A/1891</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-04">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/2215</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-05">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/2713</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-06">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/48/573</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-544-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-544-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-544-03">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/50/361</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-627-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-627-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-627-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/AC.182/L.79</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-567-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-567-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-567-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">FAO・WFPレポート(イラク制裁)</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-400-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-400-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-400-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/10865</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-04">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/1994/1265</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-538-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-538-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-538-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/1999/356</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-422-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-422-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-422-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26040</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-06">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26056</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-04">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26282</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-05">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">アガハーンレポート</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-396-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-396-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-396-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">アーティサーリレポート</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-384-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-384-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-384-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">コペンハーゲン円卓会議報告書</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-435-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-435-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-435-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-541-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-541-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-541-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題：補遺（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-584-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-584-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-584-01">4節4項</a></span></span></span>
:::

::: {.aj-index__block}
## アンゴラ

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1087</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-044-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-044-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-044-03">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/435</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-041-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-041-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-041-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/626</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-041-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-041-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-041-02">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/696</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-042-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-042-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-042-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/747</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-043-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-043-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-043-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/804</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-043-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-043-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-043-02">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/864</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-043-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-043-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-043-03">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/966</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-044-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-044-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-044-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/976</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-044-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-044-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-044-02">アンゴラ（1989年～1999年）</a></span></span></span>
:::

::: {.aj-index__block}
## イラク情勢

- <span class="aj-index__entry"><span class="aj-index__term">FAO・WFPレポート(イラク制裁)</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-400-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-400-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-400-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/1999/356</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-422-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-422-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-422-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/660</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-054-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-054-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-054-01">湾岸戦争（1990年～1991年）</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-415-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-415-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-415-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/661</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-055-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-055-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-055-01">湾岸戦争（1990年～1991年）</a></span><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-146-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-146-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-146-01">3節1項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-415-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-415-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-415-02">4節1項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-378-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-378-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-378-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/665</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-056-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-056-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-056-01">湾岸戦争（1990年～1991年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/666</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-383-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-383-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-383-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/670</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-056-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-056-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-056-02">湾岸戦争（1990年～1991年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/678</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-415-03" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-415-03" data-aj-index-local-href="02_ch02.html#idx-02-ch02-415-03">4節1項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-384-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-384-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-384-03">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-661-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-661-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-661-01">4節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/686</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-062-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-062-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-062-01">イラク（1991年～2003年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/687</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-062-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-062-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-062-02">イラク（1991年～2003年）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-057-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-057-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-057-01">湾岸戦争（1990年～1991年）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-393-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-393-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-393-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/689</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-064-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-064-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-064-01">イラク（1991年～2003年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/706</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-398-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-398-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-398-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/806</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-067-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-067-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-067-01">イラク（1991年～2003年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">アガハーンレポート</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-396-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-396-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-396-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">アーティサーリレポート</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-384-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-384-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-384-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-409-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-409-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-409-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">石油と食料交換プログラム</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-403-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-403-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-403-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対イラク制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-129-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-129-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-129-01">3節1項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-378-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-378-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-378-02">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-661-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-661-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-661-02">4節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対イラク制裁における人道危機</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-384-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-384-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-384-02">4節3項</a></span></span></span>
:::

::: {.aj-index__block}
## エルサルバドル

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/693</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-075-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-075-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-075-01">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/729</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-076-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-076-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-076-01">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/832</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-077-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-077-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-077-01">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/961</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-077-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-077-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-077-02">エルサルバドル（1991年～1995年）</a></span></span></span>
:::

::: {.aj-index__block}
## カンボジア紛争

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/717</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-094-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-094-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-094-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/745</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-095-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-095-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-095-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/792</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-096-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-096-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-096-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/840</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-097-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-097-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-097-01">カンボジア（1992年～1993年）</a></span></span></span>
:::

::: {.aj-index__block}
## キプロス

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/186</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-033-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-033-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-033-01">キプロス（1964年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/355</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-034-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-034-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-034-01">キプロス（1964年～）</a></span></span></span>
:::

::: {.aj-index__block}
## コンゴ動乱

- <span class="aj-index__entry"><span class="aj-index__term">ONUC</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-255-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-255-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-255-01">3節7項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/143</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-026-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-026-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-026-01">コンゴ動乱（1960年～1964年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/146</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-027-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-027-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-027-01">コンゴ動乱（1960年～1964年）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-028-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-028-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-028-01">コンゴ動乱（1960年～1964年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/169</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-029-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-029-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-029-01">コンゴ動乱（1960年～1964年）</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-266-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-266-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-266-01">3節7項</a></span></span></span>
:::

::: {.aj-index__block}
## ソマリア内戦

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/733</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-102-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-102-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-102-01">ソマリア内戦（1990年代初期）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/751</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-102-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-102-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-102-02">ソマリア内戦（1990年代初期）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/794</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-103-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-103-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-103-01">ソマリア内戦（1990年代初期）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/795</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-520-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-520-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-520-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNOSOM-I</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-507-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-507-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-507-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNOSOM-Ⅱ</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-530-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-530-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-530-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">史実における言及</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-030-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-030-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-030-01">2節2項</a></span></span></span>
:::

::: {.aj-index__block}
## ナミビア

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/385</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-048-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-048-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-048-01">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/431</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-048-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-048-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-048-02">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/435</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-049-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-049-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-049-01">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/629</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-050-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-050-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-050-01">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/632</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-050-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-050-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-050-02">ナミビア（1989年～1990年）</a></span></span></span>
:::

::: {.aj-index__block}
## ハイチ情勢

- <span class="aj-index__entry"><span class="aj-index__term">S/1994/1265</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-538-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-538-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-538-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/841</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-126-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-126-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-126-01">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/861</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/867</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-130-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-130-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-130-01">ハイチ（1993年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/873</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-132-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-132-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-132-01">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-03">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/875</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-132-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-132-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-132-02">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-04">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/917</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-134-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-134-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-134-01">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-523-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-523-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-523-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/940</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-134-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-134-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-134-02">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-05">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/944</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-134-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-134-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-134-03">ハイチ（1993年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/948</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-06">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-538-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-538-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-538-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ハイチ制裁における制裁の推移</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-529-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-529-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-529-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ハイチ制裁における制裁破り</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-533-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-533-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-533-01">4節3項</a></span></span></span>
:::

::: {.aj-index__block}
## モザンビーク

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/797</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-113-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-113-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-113-01">モザンビーク（1992年～1994年）</a></span></span></span>
:::

::: {.aj-index__block}
## リベリア

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/787</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-119-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-119-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-119-01">リベリア（1993年～1997年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/856</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-119-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-119-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-119-02">リベリア（1993年～1997年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/866</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-119-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-119-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-119-03">リベリア（1993年～1997年）</a></span></span></span>
:::

::: {.aj-index__block}
## ルワンダ情勢

- <span class="aj-index__entry"><span class="aj-index__term">S/PRST/1994/21</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-612-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-612-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-612-01">4節6項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1029</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-141-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-141-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-141-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/872</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-137-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-137-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-137-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/912</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-138-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-138-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-138-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/918</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-138-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-138-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-138-02">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/929</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-139-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-139-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-139-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/965</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-140-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-140-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-140-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNAMIRの展開</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-254-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-254-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-254-01">3節1項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-585-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-585-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-585-01">4節6項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-604-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-604-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-604-01">4節6項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNOMURの設立</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-581-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-581-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-581-01">4節6項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">ルワンダ内戦の経緯</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-571-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-571-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-571-01">4節6項</a></span></span></span>
:::

::: {.aj-index__block}
## 制裁

- <span class="aj-index__entry"><span class="aj-index__term">A/1891</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-04">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/2215</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-05">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/2713</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-06">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/48/573</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-544-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-544-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-544-03">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/50/361</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-627-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-627-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-627-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/51/242</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-641-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-641-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-641-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/AC.182/L.79</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-567-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-567-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-567-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/47/120B6</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-552-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-552-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-552-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">GATT協定</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-155-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-155-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-155-01">4節</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/24728</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-544-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-544-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-544-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/25036</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-544-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-544-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-544-02">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26040</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-06">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26056</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-04">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26282</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-05">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/PRST/1995/9（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-609-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-609-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-609-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/418</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-364-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-364-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-364-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/569</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-366-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-366-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-366-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/706</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-398-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-398-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-398-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">安全保障例外</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-170-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-170-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-170-01">4節</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">異議なし手続き</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-382-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-382-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-382-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">経済制裁の概要</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-287-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-287-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-287-01">4節</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-05">4節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-370-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-370-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-370-01">4節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-409-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-409-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-409-01">4節3項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-446-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-446-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-446-01">4節3項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-495-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-495-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-495-01">4節3項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-538-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-538-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-538-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">制裁の目的</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-182-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-182-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-182-01">3節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">石油と食料交換プログラム</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-403-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-403-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-403-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対抗措置</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-031-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-031-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-031-01">1節3項</a></span><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-072-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-072-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-072-01">2項</a></span><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-095-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-095-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-095-01">2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対南アフリカ制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-364-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-364-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-364-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対イタリア制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-304-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-304-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-304-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対イラク制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-378-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-378-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-378-02">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-661-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-661-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-661-02">4節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対イラク制裁における人道危機</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-384-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-384-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-384-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ザンビア支援（対南ローデシア制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-353-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-353-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-353-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ハイチ制裁における制裁の推移</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-529-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-529-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-529-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ハイチ制裁における制裁破り</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-533-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-533-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-533-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-426-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-426-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-426-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁における制裁委員会の問題</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-437-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-437-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-437-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁における制裁履行の問題</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-440-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-440-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-440-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対リビア制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-405-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-405-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-405-01">3節11項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-480-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-480-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-480-01">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-661-03" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-661-03" data-aj-index-local-href="02_ch02.html#idx-02-ch02-661-03">4節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ローデシア制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-340-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-340-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-340-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-541-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-541-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-541-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題：補遺（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-584-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-584-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-584-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">南アフリカ修正提案</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-152-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-152-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-152-01">3節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-324-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-324-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-324-01">4節1項</a></span></span></span>
:::

::: {.aj-index__block}
## 南アフリカ情勢

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/418</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-364-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-364-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-364-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/569</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-366-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-366-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-366-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-370-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-370-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-370-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対南アフリカ制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-364-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-364-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-364-01">4節2項</a></span></span></span>
:::

::: {.aj-index__block}
## 南ローデシア情勢

- <span class="aj-index__entry"><span class="aj-index__term">S/10865</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-04">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/232</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-344-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-344-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-344-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/253</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-346-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-346-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-346-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/326</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/329</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/386</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-03">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-05">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ザンビア支援（対南ローデシア制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-353-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-353-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-353-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ローデシア制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-340-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-340-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-340-01">4節2項</a></span></span></span>
:::

::: {.aj-index__block}
## 国連憲章

- <span class="aj-index__entry"><span class="aj-index__term">103条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-119-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-119-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-119-03">1節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">17条2項</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-276-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-276-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-276-02">3節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">1条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-005-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-005-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-005-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">23条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-082-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-082-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-082-01">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">24条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-073-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-073-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-073-01">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">25条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-073-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-073-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-073-02">1節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-119-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-119-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-119-01">1節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">27条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-086-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-086-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-086-01">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">2条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-005-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-005-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-005-02">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">39条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-105-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-105-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-105-01">1節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">40条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-105-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-105-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-105-02">1節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">41条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-105-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-105-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-105-03">1節3項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-305-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-305-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-305-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">42条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-105-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-105-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-105-04">1節3項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-305-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-305-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-305-02">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">48条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-119-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-119-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-119-02">1節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">49条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-308-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-308-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-308-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">50条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-308-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-308-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-308-02">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章39条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-737-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-737-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-737-01">③強制措置における正統性の制約</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章41条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-737-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-737-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-737-02">③強制措置における正統性の制約</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章43条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-272-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-272-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-272-01">3節8項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-368-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-368-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-368-01">3節10項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-433-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-433-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-433-01">4節2項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-472-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-472-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-472-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章47条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-433-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-433-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-433-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章49条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-154-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-154-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-154-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-154-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-154-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-154-02">3節1項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-156-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-156-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-156-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">ダンバートンオークス提案　第8章B節</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-318-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-318-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-318-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">米国試案（ダンバートンオークス提案）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-316-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-316-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-316-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">南アフリカ修正提案</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-152-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-152-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-152-01">3節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-324-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-324-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-324-01">4節1項</a></span></span></span>
:::

::: {.aj-index__block}
## 国連機関

- <span class="aj-index__entry"><span class="aj-index__term">IMF</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-068-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-068-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-068-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">ONUC</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-255-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-255-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-255-01">3節7項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKO特別委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-035-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-035-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-035-01">2節2項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-292-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-292-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-292-01">3節9項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-377-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-377-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-377-01">3節10項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-449-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-449-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-449-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNDP</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-064-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-064-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-064-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNIKOM</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-445-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-445-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-445-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">安全保障理事会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-072-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-072-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-072-01">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国連憲章およびその役割の強化に関する特別委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-042-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-042-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-042-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国連政治局：DPA</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-054-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-054-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-054-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">集団措置特別委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-040-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-040-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-040-01">1節1項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-03">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">人道問題局：DHA</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-057-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-057-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-057-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">制裁委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-137-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-137-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-137-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">世界銀行</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-068-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-068-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-068-02">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">第5委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-038-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-038-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-038-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">第6委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-039-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-039-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-039-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和維持活動局：DPKO</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-056-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-056-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-056-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和維持活動に関する特別委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-041-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-041-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-041-01">1節1項</a></span></span></span>
:::

::: {.aj-index__block}
## 国連緊急軍

- <span class="aj-index__entry"><span class="aj-index__term">A/RES/1000</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-04" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-04" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-04">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/997</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-02">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/998</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-03">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1000</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-009-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-009-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-009-02">国連緊急軍</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/338</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-018-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-018-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-018-01">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/339</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-018-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-018-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-018-02">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/340</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-017-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-017-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-017-01">第二次国連緊急軍（UNEFⅡ）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-017-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-017-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-017-03">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/341</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-017-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-017-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-017-02">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/998</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-009-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-009-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-009-01">国連緊急軍</a></span></span></span>
:::

::: {.aj-index__block}
## 国連（パレスチナ）休戦監視機構

- <span class="aj-index__entry"><span class="aj-index__term">A/RES/186</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-005-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-005-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-005-02">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/46</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-004-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-004-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-004-01">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/48</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-004-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-004-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-004-02">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/50</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-005-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-005-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-005-01">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/54</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-006-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-006-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-006-01">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/73</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-006-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-006-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-006-02">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
:::

::: {.aj-index__block}
## 安保理サミット

- <span class="aj-index__entry"><span class="aj-index__term">PKO特別委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-449-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-449-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-449-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKOへの各国貢献</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-438-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-438-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-438-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章43条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-433-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-433-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-433-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章47条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-433-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-433-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-433-02">4節2項</a></span></span></span>
:::

::: {.aj-index__block}
## 安保理決議

- <span class="aj-index__entry"><span class="aj-index__term">A/RES/377(V)</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-01">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1000</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-009-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-009-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-009-02">国連緊急軍</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1022</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-432-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-432-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-432-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1029</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-141-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-141-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-141-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1056</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-073-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-073-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-073-01">西サハラ（1991年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1087</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-044-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-044-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-044-03">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/143</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-026-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-026-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-026-01">コンゴ動乱（1960年～1964年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/146</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-027-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-027-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-027-01">コンゴ動乱（1960年～1964年）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-028-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-028-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-028-01">コンゴ動乱（1960年～1964年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/169</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-029-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-029-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-029-01">コンゴ動乱（1960年～1964年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/186</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-033-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-033-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-033-01">キプロス（1964年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/232</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-344-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-344-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-344-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/253</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-346-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-346-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-346-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/326</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/329</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/338</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-018-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-018-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-018-01">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/339</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-018-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-018-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-018-02">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/340</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-017-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-017-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-017-01">第二次国連緊急軍（UNEFⅡ）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-017-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-017-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-017-03">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/341</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-017-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-017-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-017-02">第二次国連緊急軍（UNEFⅡ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/355</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-034-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-034-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-034-01">キプロス（1964年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/385</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-048-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-048-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-048-01">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/386</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-361-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-361-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-361-03">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/418</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-364-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-364-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-364-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/431</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-048-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-048-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-048-02">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/435</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-041-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-041-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-041-01">アンゴラ（1989年～1999年）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-049-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-049-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-049-01">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/46</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-004-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-004-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-004-01">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/48</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-004-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-004-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-004-02">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/50</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-005-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-005-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-005-01">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/54</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-006-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-006-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-006-01">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/569</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-366-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-366-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-366-01">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/626</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-041-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-041-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-041-02">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/629</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-050-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-050-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-050-01">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/632</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-050-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-050-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-050-02">ナミビア（1989年～1990年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/660</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-054-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-054-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-054-01">湾岸戦争（1990年～1991年）</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-415-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-415-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-415-01">4節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/661</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-055-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-055-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-055-01">湾岸戦争（1990年～1991年）</a></span><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-146-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-146-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-146-01">3節1項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-415-02" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-415-02" data-aj-index-local-href="02_ch02.html#idx-02-ch02-415-02">4節1項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-378-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-378-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-378-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/665</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-056-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-056-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-056-01">湾岸戦争（1990年～1991年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/666</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-383-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-383-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-383-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/670</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-056-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-056-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-056-02">湾岸戦争（1990年～1991年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/678</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-415-03" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-415-03" data-aj-index-local-href="02_ch02.html#idx-02-ch02-415-03">4節1項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-384-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-384-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-384-03">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-661-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-661-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-661-01">4節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/686</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-062-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-062-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-062-01">イラク（1991年～2003年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/687</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-062-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-062-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-062-02">イラク（1991年～2003年）</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-057-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-057-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-057-01">湾岸戦争（1990年～1991年）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-393-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-393-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-393-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/689</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-064-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-064-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-064-01">イラク（1991年～2003年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/690</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-071-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-071-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-071-01">西サハラ（1991年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/693</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-075-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-075-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-075-01">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/696</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-042-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-042-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-042-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/706</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-398-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-398-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-398-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/713</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-080-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-080-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-080-01">クロアチア</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-427-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-427-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-427-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/717</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-094-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-094-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-094-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/724</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-427-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-427-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-427-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/729</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-076-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-076-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-076-01">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/73</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-006-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-006-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-006-02">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/733</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-102-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-102-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-102-01">ソマリア内戦（1990年代初期）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/743</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-080-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-080-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-080-02">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/745</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-095-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-095-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-095-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/747</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-043-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-043-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-043-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/748</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-482-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-482-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-482-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/751</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-102-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-102-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-102-02">ソマリア内戦（1990年代初期）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/752</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-428-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-428-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-428-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/757</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-01">ボスニア</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-428-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-428-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-428-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/761</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-02">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/762</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-081-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-081-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-081-01">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/769</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-081-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-081-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-081-02">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/770</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-03">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/779</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-081-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-081-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-081-03">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/781</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-04" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-04" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-04">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/787</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-119-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-119-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-119-01">リベリア（1993年～1997年）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-431-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-431-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-431-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/792</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-096-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-096-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-096-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/794</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-103-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-103-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-103-01">ソマリア内戦（1990年代初期）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/795</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-089-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-089-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-089-01">マケドニア</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-520-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-520-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-520-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/797</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-113-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-113-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-113-01">モザンビーク（1992年～1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/804</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-043-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-043-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-043-02">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/806</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-067-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-067-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-067-01">イラク（1991年～2003年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/816</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-05" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-05" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-05">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/819</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-085-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-085-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-085-01">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/820</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-431-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-431-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-431-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/824</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-085-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-085-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-085-02">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/832</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-077-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-077-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-077-01">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/836</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-085-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-085-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-085-03">ボスニア</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-086-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-086-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-086-01">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/840</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-097-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-097-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-097-01">カンボジア（1992年～1993年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/841</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-126-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-126-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-126-01">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/856</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-119-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-119-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-119-02">リベリア（1993年～1997年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/861</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/864</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-043-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-043-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-043-03">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/866</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-119-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-119-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-119-03">リベリア（1993年～1997年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/867</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-130-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-130-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-130-01">ハイチ（1993年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/872</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-137-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-137-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-137-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/873</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-132-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-132-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-132-01">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-03">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/875</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-132-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-132-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-132-02">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-04">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/883</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-494-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-494-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-494-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/912</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-138-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-138-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-138-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/917</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-134-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-134-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-134-01">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-523-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-523-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-523-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/918</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-138-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-138-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-138-02">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/929</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-139-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-139-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-139-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/940</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-134-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-134-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-134-02">ハイチ（1993年～）</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-05">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/944</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-134-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-134-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-134-03">ハイチ（1993年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/948</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-496-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-496-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-496-06">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/961</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-077-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-077-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-077-02">エルサルバドル（1991年～1995年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/965</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-140-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-140-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-140-01">ルワンダ内戦（1994年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/966</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-044-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-044-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-044-01">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/976</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-044-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-044-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-044-02">アンゴラ（1989年～1999年）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/981</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-083-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-083-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-083-01">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/983</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-091-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-091-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-091-01">マケドニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/998</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-009-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-009-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-009-01">国連緊急軍</a></span></span></span>
:::

::: {.aj-index__block}
## 対リビア制裁

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/748</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-482-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-482-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-482-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/883</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-494-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-494-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-494-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-495-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-495-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-495-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対リビア制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-129-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-129-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-129-02">3節1項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-405-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-405-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-405-01">3節11項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-480-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-480-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-480-01">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-661-03" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-661-03" data-aj-index-local-href="02_ch02.html#idx-02-ch02-661-03">4節8項</a></span></span></span>
:::

::: {.aj-index__block}
## 旧ユーゴスラビア内戦

- <span class="aj-index__entry"><span class="aj-index__term">A/RES/48/210</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26040</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-06" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-06" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-06">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26056</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-04" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-04" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-04">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/26282</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-05" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-05" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-05">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1022</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-432-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-432-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-432-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/713</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-080-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-080-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-080-01">クロアチア</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-427-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-427-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-427-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/724</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-427-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-427-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-427-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/743</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-080-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-080-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-080-02">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/752</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-428-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-428-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-428-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/757</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-01">ボスニア</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-428-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-428-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-428-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/761</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-02">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/762</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-081-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-081-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-081-01">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/769</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-081-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-081-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-081-02">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/770</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-03">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/779</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-081-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-081-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-081-03">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/781</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-04" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-04" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-04">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/787</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-431-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-431-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-431-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/795</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-089-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-089-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-089-01">マケドニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/816</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-084-05" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-084-05" data-aj-index-local-href="04_ch04.html#idx-04-ch04-084-05">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/819</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-085-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-085-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-085-01">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/820</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-431-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-431-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-431-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/824</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-085-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-085-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-085-02">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/836</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-085-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-085-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-085-03">ボスニア</a></span><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-086-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-086-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-086-01">ボスニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/981</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-083-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-083-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-083-01">クロアチア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/983</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-091-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-091-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-091-01">マケドニア</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">UNPROFORの展開</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-256-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-256-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-256-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条の協議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-446-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-446-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-446-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">コペンハーゲン円卓会議報告書</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-435-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-435-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-435-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">史実における言及</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-030-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-030-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-030-02">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-426-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-426-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-426-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁における制裁委員会の問題</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-437-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-437-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-437-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁における制裁履行の問題</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-440-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-440-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-440-01">4節3項</a></span></span></span>
:::

::: {.aj-index__block}
## 総会決議

- <span class="aj-index__entry"><span class="aj-index__term">A/51/242</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-641-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-641-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-641-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/1000</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-04" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-04" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-04">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/186</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-005-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-005-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-005-02">国連（パレスチナ）休戦監視機構（1948年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/1874</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-227-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-227-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-227-02">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/377</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-02">4節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/47/120B6</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-552-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-552-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-552-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/48/210</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/48/43</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-258-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-258-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-258-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/49/21</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-02">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/50/58E</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-475-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-475-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-475-03">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/997</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-02" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-02" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-02">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/RES/998</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-012-03" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-012-03" data-aj-index-local-href="04_ch04.html#idx-04-ch04-012-03">第一次国連緊急軍（UNEFⅠ）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">不干渉原則宣言</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-012-02" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-012-02" data-aj-index-local-href="06_ch06.html#idx-06-ch06-012-02">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和の為の結集決議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-335-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-335-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-335-01">4節2項</a></span></span></span>
:::

::: {.aj-index__block}
## 補遺と史実の議論

- <span class="aj-index__entry"><span class="aj-index__term">A/50/361</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-627-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-627-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-627-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">A/51/242</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-641-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-641-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-641-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/PRST/1995/9（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-183-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-183-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-183-01">3節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-609-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-609-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-609-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">旧ユーゴスラビア内戦</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-082-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-082-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-082-02">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">緊急対応部隊</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-069-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-069-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-069-01">2節2項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-112-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-112-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-112-02">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章43条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-083-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-083-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-083-01">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章49条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-154-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-154-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-154-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">憲章50条</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-154-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-154-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-154-02">3節1項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-156-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-156-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-156-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国連早期展開旅団</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-074-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-074-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-074-01">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国連待機制度</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-057-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-057-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-057-01">2節2項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-068-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-068-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-068-01">2節2項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-085-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-085-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-085-01">2節3項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-090-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-090-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-090-01">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">史実における言及</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-030-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-030-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-030-01">2節2項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-030-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-030-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-030-02">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">制裁委員会</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-137-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-137-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-137-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">制裁の目的</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-182-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-182-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-182-01">3節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">即応部隊の撤退</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-091-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-091-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-091-01">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">ソマリア内戦</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-082-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-082-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-082-01">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">待機取極制度</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-112-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-112-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-112-01">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">第三国被害</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-153-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-153-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-153-01">3節1項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-162-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-162-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-162-01">3節1項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-170-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-170-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-170-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対イラク制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-129-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-129-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-129-01">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ハイチ制裁における制裁破り</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-143-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-143-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-143-01">3節1項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-143-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-143-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-143-02">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対ユーゴ制裁における制裁破り</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-143-03" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-143-03" data-aj-index-local-href="03_ch03.html#idx-03-ch03-143-03">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">対リビア制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-129-02" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-129-02" data-aj-index-local-href="03_ch03.html#idx-03-ch03-129-02">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">部隊編成</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-089-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-089-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-089-01">2節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和強制部隊</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-023-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-023-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-023-01">2節2項</a></span><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-033-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-033-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-033-01">2節2項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-474-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-474-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-474-01">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-643-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-643-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-643-01">4節7項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-686-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-686-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-686-01">4節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-453-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-453-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-453-01">4節3項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-461-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-461-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-461-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題:制裁</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-500-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-500-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-500-01">4節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-541-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-541-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-541-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">平和への課題：補遺（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-584-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-584-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-584-01">4節4項</a></span></span></span>
:::

::: {.aj-index__block}
## 西サハラ

- <span class="aj-index__entry"><span class="aj-index__term">S/RES/1056</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-073-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-073-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-073-01">西サハラ（1991年～）</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/RES/690</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/04_ch04.html#idx-04-ch04-071-01" data-aj-index-root-href="content/04_ch04.html#idx-04-ch04-071-01" data-aj-index-local-href="04_ch04.html#idx-04-ch04-071-01">西サハラ（1991年～）</a></span></span></span>
:::

::: {.aj-index__block}
## 議長声明

- <span class="aj-index__entry"><span class="aj-index__term">S/24728</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-544-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-544-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-544-01">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/25036</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-544-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-544-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-544-02">4節4項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/PRST/1994/22</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-258-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-258-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-258-02">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/PRST/1994/62</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-258-03" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-258-03" data-aj-index-local-href="05_ch05.html#idx-05-ch05-258-03">3節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">S/PRST/1995/9（制裁）</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/03_ch03.html#idx-03-ch03-183-01" data-aj-index-root-href="content/03_ch03.html#idx-03-ch03-183-01" data-aj-index-local-href="03_ch03.html#idx-03-ch03-183-01">3節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-609-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-609-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-609-01">4節4項</a></span></span></span>
:::

::: {.aj-index__block}
## ア段

- <span class="aj-index__entry"><span class="aj-index__term">ある種の経費事件</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-270-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-270-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-270-01">3節8項</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-279-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-279-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-279-01">3節8項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">安保理改革</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-780-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-780-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-780-01">会議時点での安保理改革</a></span><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-739-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-739-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-739-01">安保理改革の前提</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">安保理議長声明</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-099-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-099-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-099-01">1節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">安保理決議</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-097-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-097-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-097-01">1節2項</a></span></span></span>
:::

::: {.aj-index__block}
## カ段

- <span class="aj-index__entry"><span class="aj-index__term">慣習法</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-008-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-008-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-008-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">脅威認定</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-111-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-111-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-111-01">1節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">国際法の法源</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-004-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-004-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-004-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">この機構の経費</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/02_ch02.html#idx-02-ch02-276-01" data-aj-index-root-href="content/02_ch02.html#idx-02-ch02-276-01" data-aj-index-local-href="02_ch02.html#idx-02-ch02-276-01">3節8項</a></span></span></span>
:::

::: {.aj-index__block}
## サ段

- <span class="aj-index__entry"><span class="aj-index__term">財政改革-平和への課題</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-235-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-235-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-235-01">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">条約</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-005-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-005-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-005-01">1節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">ソフトロー/ハードロー</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-010-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-010-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-010-01">1節1項</a></span></span></span>
:::

::: {.aj-index__block}
## タ段

- <span class="aj-index__entry"><span class="aj-index__term">通常予算</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-144-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-144-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-144-01">2節1項</a></span></span></span>
:::

::: {.aj-index__block}
## ハ段

- <span class="aj-index__entry"><span class="aj-index__term">必要なあらゆる手段</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-112-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-112-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-112-01">1節3項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">フランス軍迅速対応部隊</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-285-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-285-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-285-01">3節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">分担金</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-147-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-147-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-147-01">2節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">分担金-PKO分担金</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-227-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-227-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-227-01">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">分担金-自発的拠出方式</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-225-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-225-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-225-01">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">分担金-通常予算方式</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-224-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-224-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-224-01">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">分担金の滞納</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-149-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-149-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-149-01">2節1項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">法の一般原則</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/06_ch06.html#idx-06-ch06-009-01" data-aj-index-root-href="content/06_ch06.html#idx-06-ch06-009-01" data-aj-index-local-href="06_ch06.html#idx-06-ch06-009-01">1節1項</a></span></span></span>
:::

::: {.aj-index__block}
## アルファベット・数字

- <span class="aj-index__entry"><span class="aj-index__term">CENTCOM</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-285-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-285-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-285-02">3節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PDD-25</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-239-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-239-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-239-01">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKO償還金</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-221-02" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-221-02" data-aj-index-local-href="05_ch05.html#idx-05-ch05-221-02">2節2項</a></span></span></span>
- <span class="aj-index__entry"><span class="aj-index__term">PKO予算</span><span class="aj-index__dots">…</span><span class="aj-index__locations"><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-217-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-217-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-217-01">2節2項</a></span><span class="aj-index__loc"><a href="content/05_ch05.html#idx-05-ch05-221-01" data-aj-index-root-href="content/05_ch05.html#idx-05-ch05-221-01" data-aj-index-local-href="05_ch05.html#idx-05-ch05-221-01">2節2項</a></span></span></span>
:::
:::
