#!/usr/bin/env python3
"""
Extract fine-grained page boundary data from LaTeX .boundaries file.
Generates enhanced JSON with chunk-level position tracking.

The .boundaries file is generated by page-boundary-macros.tex during LaTeX compilation.
Format:
  CHUNK:para-id:chunk-id:char-offset:page:lastypos
  FLOAT:id:type:page:lastypos
  BOUNDARY:before-para:after-para:page
  END_OF_BOUNDARIES

Where lastypos is in sp (scaled point) units = 1/65536pt
"""

import re
import json
import sys
from pathlib import Path
from typing import Dict, List, Any


def parse_boundaries_file(boundaries_path: Path) -> Dict[str, Any]:
    """
    Parse the .boundaries file generated by LaTeX boundary markers.

    Returns dict with:
      - chunks: list of chunk data with page and y-position
      - floats: list of float data with actual publication pages
      - boundaries: list of boundary separators
    """
    chunks = []
    floats = []
    boundaries = []

    if not boundaries_path.exists():
        print(f"Warning: .boundaries file not found: {boundaries_path}", file=sys.stderr)
        return {"chunks": chunks, "floats": floats, "boundaries": boundaries}

    with open(boundaries_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if not line or line == 'END_OF_BOUNDARIES':
                continue

            if line.startswith('CHUNK:'):
                # CHUNK:para-id:chunk-id:char-offset:page:lastypos
                parts = line.split(':', 5)
                if len(parts) >= 6:
                    try:
                        y_pos_sp = int(parts[5])
                        # Convert sp to normalized page position (0-1, where 0=bottom, 1=top)
                        # Assuming A4 page height ≈ 794pt (11 inch), so y_pos / (page_height * 65536)
                        # For simplicity, we'll store the raw sp and let frontend normalize
                        chunks.append({
                            "paragraphId": parts[1],
                            "id": parts[2],
                            "charOffset": int(parts[3]),
                            "page": int(parts[4]),
                            "yPositionSp": y_pos_sp,
                            # Normalized estimate (assuming ~750pt page height)
                            "yPosition": min(1.0, max(0.0, y_pos_sp / (750 * 65536)))
                        })
                    except (ValueError, IndexError):
                        continue

            elif line.startswith('FLOAT:'):
                # FLOAT:id:type:page:lastypos
                parts = line.split(':', 4)
                if len(parts) >= 5:
                    try:
                        floats.append({
                            "id": parts[1],
                            "type": parts[2],
                            "actualPage": int(parts[3]),
                            "yPositionSp": int(parts[4])
                        })
                    except (ValueError, IndexError):
                        continue

            elif line.startswith('BOUNDARY:'):
                # BOUNDARY:before-para:after-para:page
                parts = line.split(':', 3)
                if len(parts) >= 4:
                    try:
                        boundaries.append({
                            "beforeParagraph": parts[1],
                            "afterParagraph": parts[2],
                            "pageNumber": int(parts[3])
                        })
                    except (ValueError, IndexError):
                        continue

    return {"chunks": chunks, "floats": floats, "boundaries": boundaries}


def detect_boundaries_from_mapping(page_mapping: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Detect page boundaries from existing paragraph-to-page mapping.

    Finds paragraphs that span page boundaries by looking for
    consecutive paragraphs on different pages.
    """
    paragraphs = page_mapping.get("paragraphs", {})
    if not paragraphs:
        return []

    # Group paragraphs by page
    pages_to_paras: Dict[int, List[str]] = {}
    for para_id, page_num in paragraphs.items():
        if page_num not in pages_to_paras:
            pages_to_paras[page_num] = []
        pages_to_paras[page_num].append(para_id)

    # Sort pages
    sorted_pages = sorted(pages_to_paras.keys())

    boundaries = []
    for i in range(len(sorted_pages) - 1):
        current_page = sorted_pages[i]
        next_page = sorted_pages[i + 1]

        # Get last paragraph on current page and first on next page
        current_paras = sorted(pages_to_paras[current_page], key=lambda x: int(x.split('-')[1]))
        next_paras = sorted(pages_to_paras[next_page], key=lambda x: int(x.split('-')[1]))

        if current_paras and next_paras:
            boundaries.append({
                "pageNumber": next_page,
                "beforeParagraph": current_paras[-1],
                "afterParagraph": next_paras[0]
            })

    return boundaries


def enhance_page_mapping(
    base_mapping_path: Path,
    boundaries_data: Dict[str, Any],
    output_path: Path
) -> Dict[str, Any]:
    """
    Enhance existing page mapping with fine-grained boundary data.

    Creates enhanced JSON with:
      - Original paragraphs/sections mapping
      - Boundary chunks with page and y-position
      - Float tracking data
    """
    # Load base mapping
    base_mapping = {}
    if base_mapping_path.exists():
        base_mapping = json.loads(base_mapping_path.read_text(encoding='utf-8'))

    # Group chunks by paragraph for easier lookup
    chunks_by_para: Dict[str, List[Dict]] = {}
    for chunk in boundaries_data.get("chunks", []):
        para_id = chunk.get("paragraphId")
        if para_id:
            if para_id not in chunks_by_para:
                chunks_by_para[para_id] = []
            chunks_by_para[para_id].append(chunk)

    # Build enhanced boundaries list
    # Combine detected boundaries with chunk data
    detected_boundaries = detect_boundaries_from_mapping(base_mapping)
    enhanced_boundaries = []

    for boundary in detected_boundaries:
        before_para = boundary["beforeParagraph"]
        after_para = boundary["afterParagraph"]
        page_num = boundary["pageNumber"]

        # Get chunks for this boundary region
        before_chunks = chunks_by_para.get(before_para, [])
        after_chunks = chunks_by_para.get(after_para, [])

        # Calculate break position (average y of last chunk on page)
        break_y = 0.5  # default middle
        if before_chunks:
            # Get the lowest y (closest to bottom) from before chunks
            break_y = min(c.get("yPosition", 0.5) for c in before_chunks)

        enhanced_boundaries.append({
            "pageNumber": page_num,
            "beforeParagraph": before_para,
            "afterParagraph": after_para,
            "chunks": before_chunks + after_chunks,
            "breakYPosition": break_y
        })

    # Build result
    result = {
        "version": "2.0",
        "totalPages": base_mapping.get("totalPages", 0),
        "paragraphs": base_mapping.get("paragraphs", {}),
        "sections": base_mapping.get("sections", {}),
        "boundaries": enhanced_boundaries,
        "floats": boundaries_data.get("floats", []),
        # HTML anchor positions for scrolling (optional, can be extended)
        "htmlAnchors": {}
    }

    # Write enhanced JSON
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding='utf-8')

    # Also write JS output
    js_output_path = output_path.with_suffix('.js')
    js_content = f"window.enhancedPdfPageMapping = {json.dumps(result, ensure_ascii=False)};"
    js_output_path.write_text(js_content, encoding='utf-8')

    print(f"✓ Enhanced page mapping generated:")
    print(f"  Total pages: {result['totalPages']}")
    print(f"  Boundaries: {len(enhanced_boundaries)}")
    print(f"  Chunks tracked: {len(boundaries_data.get('chunks', []))}")
    print(f"  Floats tracked: {len(boundaries_data.get('floats', []))}")
    print(f"  JSON: {output_path}")
    print(f"  JS: {js_output_path}")

    return result


def main():
    if len(sys.argv) < 2:
        # Default paths
        project_root = Path(__file__).parent.parent
        boundaries_path = project_root / "index.boundaries"
        base_mapping_path = project_root / "out" / "assets" / "pdf-page-map.json"
        output_path = project_root / "out" / "assets" / "pdf-page-map-enhanced.json"
    else:
        boundaries_path = Path(sys.argv[1])
        base_mapping_path = Path(sys.argv[2]) if len(sys.argv) > 2 else None
        output_path = Path(sys.argv[3]) if len(sys.argv) > 3 else Path("pdf-page-map-enhanced.json")

    # Parse boundaries file
    boundaries_data = parse_boundaries_file(boundaries_path)

    # Determine base mapping path
    if base_mapping_path is None:
        project_root = Path(__file__).parent.parent
        base_mapping_path = project_root / "out" / "assets" / "pdf-page-map.json"

    # Enhance and output
    enhance_page_mapping(base_mapping_path, boundaries_data, output_path)


if __name__ == "__main__":
    main()
