-- PDF Index Styling Filter
-- Changed to use QMD-generated index content instead of LaTeX's imakeidx
-- The index structure is generated by build_book_index_v2.py with proper
-- category ordering and sorting

-- Debug flag
local DEBUG = false

-- Track if we're in index section
local in_index = false

local function is_fullpage_image_block(block)
  if block.t == "Para" and block.content and #block.content == 1 then
    local inline = block.content[1]
    if inline.t == "Image" and inline.classes and inline.classes:includes("fullpage-image") then
      return true
    end
  end

  if block.t == "Div" and block.classes and block.classes:includes("fullpage-image") then
    return true
  end

  return false
end

local function sanitize_index_block(block)
  return block:walk({
    RawInline = function(el)
      if el.format ~= "latex" then
        return nil
      end

      local page = el.text:match("^\\hyperpage%{(%d+)%}$")
      if not page then
        return nil
      end

      return pandoc.Str(page)
    end
  })
end

function Pandoc(doc)
  -- For PDF output, we now keep the QMD-generated index content
  -- instead of replacing it with \printindex
  -- The index_category_pdf.lua filter will style the category headers
  
  local new_blocks = pandoc.List()
  in_index = false
  
  for _, block in ipairs(doc.blocks) do
    -- Detect start of index section by H1 header containing "索引"
    if block.t == "Header" and block.level == 1 then
      local header_text = pandoc.utils.stringify(block)
      if header_text:match("索引") then
        if not in_index then
          in_index = true
          -- Insert a chapter header for the index with custom list styling.
          -- Quarto can emit both the document title and the explicit # 索引
          -- heading as level-1 blocks; only the first should open multicols.
          new_blocks:insert(pandoc.RawBlock("latex", [[
% 索引セクション開始
\clearpage
\chapter*{索引}
\addcontentsline{toc}{chapter}{索引}
\markboth{索引}{索引}
\markright{索引}

% 索引は2段組
\begin{multicols*}{2}
\raggedcolumns

% 索引用フォントサイズとリストスタイル
\fontsize{10.5pt}{14.4pt}\selectfont
\setlength{\parskip}{0pt}

% 箇条書きインデント調整（全角1文字分 ≈ 1em）
\setlist[itemize,1]{leftmargin=1em, labelsep=0.3em, itemsep=0.5pt, parsep=0pt, topsep=2pt}

% 箇条書きの点を小さく
\renewcommand{\labelitemi}{\tiny$\bullet$}
]]))
        end
      else
        -- Non-index H1
        if in_index then
          -- Restore normal size and list settings
          new_blocks:insert(pandoc.RawBlock("latex", [[
% 索引セクション終了
\end{multicols*}
\normalsize
\setlist[itemize,1]{leftmargin=*, labelsep=*}
\renewcommand{\labelitemi}{\textbullet}
]]))
          in_index = false
        end
        new_blocks:insert(block)
      end
    elseif in_index then
      if is_fullpage_image_block(block) then
        -- Full-page image chapters that follow the index should restore
        -- index-local formatting first.
        new_blocks:insert(pandoc.RawBlock("latex", [[
% 索引セクション終了（fullpage image前）
\end{multicols*}
\normalsize
\setlist[itemize,1]{leftmargin=*, labelsep=*}
\renewcommand{\labelitemi}{\textbullet}
]]))
        in_index = false
        new_blocks:insert(block)
      else
        -- Keep all index content
        new_blocks:insert(sanitize_index_block(block))
        if DEBUG then
          print("Keeping index content: " .. block.t)
        end
      end
    else
      new_blocks:insert(block)
    end
  end
  
  -- Restore normal size at end if still in index section
  if in_index then
    new_blocks:insert(pandoc.RawBlock("latex", [[
% 索引セクション終了
\end{multicols*}
\normalsize
\setlist[itemize,1]{leftmargin=*, labelsep=*}
\renewcommand{\labelitemi}{\textbullet}
]]))
  end
  
  return pandoc.Pandoc(new_blocks, doc.meta)
end

return {
  { Pandoc = Pandoc }
}
